name: Linting with black

on:
  push:
  pull_request:
      
jobs:

  black-linting:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Format code with black
        run: |
          pip install black
          black . --exclude "main.py"
